version: '3.7'

services:
  auth:
    container_name: api
    build:
      context: .
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/auth/node_modules
    ports:
      - 3010:3010
    environment:
      NODE_ENV: development
    env_file:
      - .env

  redis:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"
    image: "redis:7.2.1-bookworm"
    profiles: ["redis"]
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    # volumes:
      # - "redis:/data"